name: 'Purdue SoCET CI'
author: 'MArndt26'
description: 'Continuous Integration for Open Source ASIC'
inputs:
  targets:
    description: 'list of FuseSoC commands to run'
    required: true
    default: "echo 'No Test Targets Specified! && exit 1'"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
