# Used to Build Image for ghrc

FROM ubuntu:latest

RUN apt-get update
RUN apt-get install --no-install-recommends --yes git python3 python3-pip ssh make perl g++
RUN pip3 install fusesoc
RUN mkdir ~/.ssh
RUN ssh-keyscan github.com >>~/.ssh/known_hosts

# clean build dependencies
RUN apt remove python3-pip

# Install Verilator
COPY bin /usr/local/bin